apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.2
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
        ports:
        - containerPort: 5000
          name: tcp-input
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
    }
    output {
      stdout { codec => rubydebug }
      elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: tcp-input
  type: NodePort  # Expose port via NodePort to test from your host machine
